phamos-eu/phamos

- phamos/hooks.py
- phamos/phamos/doctype/accounting_receipt/accounting_receipt.py
- phamos/public/js/issue.js
https://github.com/phamos-eu/phamos/issues/1
- Added button Create -> Accounting Receipt in Issue
- Copies over Subject as title, Customer, Project
- Adds email communication as comment in Accounting Receipt
- Attachments are transferred from email to attachments in Accounting Receipt
- Added field in reference section on Issue for Accounting Receipt
- And added condition if Accounting Receipt reference exists, button will not show
@wojosc @roquegv @beingeek Please review
> feat: Accounting Receipt from Issue

- phamos/phamos/doctype/timesheet_record/timesheet_record.json
**Goal:** 
Delete `activity_doctype` and `activity_docname`, and merge `percent_billable` into the same column as `from_time` and `expected_time`. 
Instead of immediate deletion, we'll initially hide `activity_doctype` and `activity_docname`. After a few weeks, we'll finally delete them. 
The `column_break_zgqwu` has been removed.
Start state with changes in red:
Desired outcome:
> Hide activity_doctype and actvity_docname and delete column_break_zgqwu in Timesheet Record

- phamos/phamos/page/project_action_panel/project_action_panel.js
Correct Spelling of column in Datatable - Spend Submitted Hrs and update clickable references. 
2. add current window url instead of hard coded url to link references
Opened Project in next window
Opened Customer in next window
> feat:spell correct for spent submmited hours

- phamos/patches.txt
- phamos/patches/v1_0/add_custom_fields_for_project.py
- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
1. Add a "percent_billable" field in the Project, with a default value of 100.
2. Fetch the "percent_billable" field to the Project Action Panel.
3. Relocate the "Timesheet Calendar View" button.
4. Minimize the font size of 'Project Action Panel'.
> add percent_billable field ,change location of button 'Timesheet Calender View'

- phamos/phamos/doctype/accounting_receipt/accounting_receipt.js
- phamos/phamos/doctype/accounting_receipt/accounting_receipt.json
_In this PR we have added a functionality that will give preview of the attached PDF document in the attachment field in doclevel, to acheive this task we have added some changes which are mentioned below._
- Added html field name **_PDF Preview_** in **Accounting Receipt** doctype level
- Added a functionality that will show the preview of the PDF document.
- <img width="1378" alt="Screenshot 2024-05-28 at 16 56 48" src="https://github.com/phamos-eu/phamos/assets/14124603/845aeab6-1f90-4dc8-b240-d41ea210b1d1">
- ![recording-pdfpreview](https://github.com/phamos-eu/phamos/assets/14124603/a45356a2-588a-40fb-aa68-1dfceec97153)
> PHAMOS#31 - PDF Preview of Document

- phamos/phamos/page/project_action_panel/project_action_panel.js
1. Program added to reload only the DataTable instead of the whole page.
2. After submitting the 'Start' button dialog box, the DataTable will reload, and you will see the updated data.
3. After submitting the 'Stop' button dialog box, the DataTable will reload, and you will see the updated data.
> feat:minimize reload time of project action panel

- phamos/phamos/doctype/timesheet_record/timesheet_record.py
- phamos/phamos/page/project_action_panel/project_action_panel.js
1. Description added to 'Goal' field in Start Dialog box.
2. Description added to 'What I did' field in Stop Dialog box.
> feat:add msg after start and stop dialog box

- phamos/custom_scripts/custom_python/mattermost_daily_thread.py
- phamos/custom_scripts/custom_python/thoughtOftheDay.txt
- phamos/phamos/doctype/mattermost_channel/mattermost_channel.json
- phamos/phamos/doctype/mattermost_channel/mattermost_channel.py
- phamos/phamos/doctype/phamos_settings/phamos_settings.js
- phamos/phamos/doctype/phamos_settings/phamos_settings.json
1. Add a child table named 'Mattermost Channel' to the 'Phamos Settings' table.
2. Validation added: Only one Mattermost Channel can be enabled at a time.
3. A thread will be created in the enabled channel at the selected time.
> Update Mattermost Channel in phamos Settings

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
In Project Action Panel:
Add a Task field in the Start Dialog Box on the Project Action Panel page.
The Task should be a link field.
Add a filter to the Task field to show only tasks related to the selected project.
Save the selected Task in the Timesheet record.
> feat:add task in project action panel

- phamos/custom_scripts/custom_python/mattermost_daily_thread.py
- phamos/phamos/doctype/phamos_settings/phamos_settings.json
✅ Daily Message via API ✅ 
https://chat.phamos.eu/phamos/pl/doh97u7p7jdpf8fyp1z56fo83c
Add a "Last Daily Thread Creation Date" field in phamos Settings.
Update today's date to "Last Daily Thread Creation" after creating a thread.
If the system attempts to create a thread again, add a validation to check if "Last Daily Thread Creation" matches today's date. If it does, the thread will not be created.
> feat:add validation to avoid duplocation of daily thread creation

- phamos/phamos/page/project_action_panel/project_action_panel.js
upgrade the UI/UX of the Project Action Panel
https://git.phamos.eu/phamos/phamos/-/work_items/97#note_10356
add colors to hours headers and rows.
> add colors to hours header and rows

- phamos/phamos/doctype/implementation/implementation.js
- phamos/phamos/doctype/implementation/implementation.json
- phamos/phamos/doctype/implementation/implementation.py
- phamos/phamos/doctype/implementation/test_implementation.py
**Gitlab Issue:** 
- https://git.phamos.eu/phamos/phamos/-/work_items/33
**Summary of Requirement**
The requirement is to redo the `Implementation` doctype as is on the Production environment. Both replicate the form and the list view.
The Implementation change is showed on the GIF below;
- Added all the fields
- Filtered the Account Manager field to allow only Users with `Account Manager` role
- Added relevant fields to the listview
**The Implementation on the `Production` Environment is reflected in screenshots below**
**The Implementation I did is as in screenshots below**
> Add and Track Implementation Doctype to the phamos app

- phamos/phamos/page/project_action_panel/project_action_panel.js
https://git.phamos.eu/phamos/phamos/-/work_items/143
Updated from_time and expected_time fields in Project Action Panel.
Removed field activity_type. because it declared but never used.
> Updated missing fields in Project Action Panel

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
Issue => https://git.phamos.eu/phamos/phamos/-/work_items/122
Parent Issue => https://git.phamos.eu/phamos/phamos/-/issues/79
In this update, I have added a feature to display the total hours worked and the billable hours for every employee in the Project Action Panel. This allows employees to quickly see their total work hours and the portion of those hours that are billable, broken down by Today, This Week, and This Month.
Update format_duration to Return Integer Values and Remove Minutes:
**Before**
**After**
> Display billable hours in project action panel #122

- phamos/phamos/page/project_action_panel/project_action_panel.py
issue = > https://git.phamos.eu/phamos/phamos/-/work_items/142
Parent Issue => https://git.phamos.eu/phamos/phamos/-/issues/79
**Objective:**
The original SQL query was modified to improve the ordering of projects based on the latest update in the tabTimesheet Record table. The new query ensures that projects with the most recent timesheet records (based on creation/update timestamps) are prioritized.
Additionally, we fixed a issue where projects without a linked timesheet record could still be ordered incorrectly.
**Consistency of Data:**
- The structure and fields of the query remain largely unchanged to ensure backward compatibility with any existing frontend or functionality that relies on the previous data format.
- Only the ordering logic was updated to reflect the priority of …
> Sorting order of Your Projects

- phamos/phamos/page/project_action_panel/project_action_panel.py
**issue:**   https://git.phamos.eu/phamos/phamos/-/work_items/142
**Parent Issue:** https://git.phamos.eu/phamos/phamos/-/issues/79
**Handling Sorting of Projects with No Last Timesheet Update**
- The issue occurs because projects without a last_timesheet_update (i.e., None or NULL values) are appearing at the top instead of the bottom.
- This happens because the system treats missing values as the most recent timestamps, pushing them ahead of properly updated records.
- To fix this, we need to ensure that projects with no updates are treated as the oldest instead of the newest when sorting.
> fixed #142: Sorting order of Your Projects

- phamos/phamos/page/project_action_panel/project_action_panel.py
issue: https://git.phamos.eu/phamos/phamos/-/work_items/159
Parent Issue: https://git.phamos.eu/phamos/phamos/-/issues/158
Description:
Declare the variable total_billable_time_str with a default value of "0 billable hours" to prevent the error UnboundLocalError: cannot access local variable 'total_billable_time_str' before it is assigned a value.
> fixed issue #159: Total billable hours bug Project Action Panel

- phamos/phamos/doctype/timesheet_record/timesheet_record.py
**Parent:** https://git.phamos.eu/phamos/phamos/-/issues/146
**Child:** https://git.phamos.eu/phamos/phamos/-/work_items/147
This PR modifies the timesheet record script to ensure that the project value is stored in the correct standard field when mapping a timesheet record to the timesheet form.
> [#147][Corrected the timesheet record script]

- phamos/phamos/doctype/implementation/implementation.js
- phamos/phamos/doctype/implementation/implementation.json
- phamos/phamos/doctype/implementation/implementation.py
**Radar chart for modules level**
Added a radar chart in the module tab of Implementation Doctype to show the progress of the current-level and the target-level of the modules
* \[Added 2 HTML fields in the Implementation doctype ]
* 1 field is for the radar chart and the second field is to show text "Target Level 0-10 (0= not implementing, 10 = full implementation, 5 = basic implementation )"
* Also resolve the issue caused by the get_financial_history() function, for this function customer is taking as an argument but for now we add "internal implementation check" for this customer is not mandatory to I write here that if customer = None than no need to run this function
Display modules in implementation (issue #146) Done …
> radar chart for modules level

- phamos/phamos/doctype/implementation/implementation.js
- phamos/phamos/doctype/implementation/implementation.json
- phamos/phamos/doctype/implementation/implementation.py
**Updating of status options (#172)**
Fields are renamed and delete mood field also replaced some of the fields in the Implementation doctype.
* "mood" field removed
* "Status" Text field renamed to "Status Statement"
* "Status Statement" moved to be located below "Forecast"
* "Forecast" renamed to "Implementation Status" 
* "Trend" field added below "Status" (formally forecast") with three options (Improving,Stable,Declining)
* Maturity Level options updated In English
[#174](https://git.phamos.eu/phamos/phamos/-/work_items/174)
Testing is done on my Local 
**Screenshots & GIFs (if applicable):**
> Updating of status options (#172)

- phamos/phamos/doctype/resource_planning/resource_planning.json
This error is occurring because some of the existing records in the Resource Planning table already have values in the billable_time_spent, non_billable_time_spent, and total_time fields. These values were previously stored as Data type (e.g., strings like '79.4885'), and the system is now trying to convert them to an Integer, which causes the migration to fail.
I’ve changed the field type from Int to Float instead. This is more appropriate because the original data contains decimal values, and for reporting (especially for graphs where we sum up billable/non-billable time), it's important to preserve decimal precision.
Issue: Add resource estimation for future work (#161)
Parent: …
> resolved error on migration

- phamos/phamos/page/project_action_panel/project_action_panel.js
Issue: https://git.phamos.eu/phamos/phamos/-/issues/192
Description:
This PR introduces change in the order of the fields in project action panel.
Current field order:
Time
Activity Type
What I did
New field order:
What I did
Activity Type
Time
> Hotfix:Reorder of fields

- phamos/api.py
- phamos/www/timesheet/index.html
- phamos/www/timesheet/index.js
Added graph in the **Customer Timesheet Portal** which shows points/data on a weekly basis.
- **Html file:** Added  div for the graph
- **Py file:** Get data from the tabTimesheet.
- **js file:** get a chart from **highcharts** and make it weekly basis which means weeks start on monday and ends on sunday.
- Also filter end_date, start_date and project are applicable.
Issue: Implementing Dashboard with graph
Parent Issue : https://git.phamos.eu/phamos/phamos/-/issues/191
Working fine on local machine
**Screenshots & GIFs (if applicable):**
> Graph in timesheet portal

- phamos/patches.txt
- phamos/patches/v1_0/set_implementation_status.py
- phamos/patches/v1_0/updated_maturity_levels.py
- phamos/phamos/doctype/implementation/implementation.json
- phamos/phamos/doctype/implementation/implementation.py
- phamos/phamos/doctype/status_information/status_information.json
Updation in maturity levels and other fields in Implementation doctype. Also removed issue after deleting "mood" field.
* The mood field was removed in the "Details" and "Status History" tab.
* "Forecast" (in history tab) changed to "Implementation Status"
* "Trend" column added to history tab
* "Status Statement" column added to history tab
* Updated Maturity Level.
* Also Write a Patch to update the previous Maturity Level/ set implementation status to open.
* Remove error coming on saving implementation after deleting "mood" field
Issue: Updating of status options (#172)
Parent Issue: phamos/phamos#172
Tested on local system found issue after deleting mood field but now it is working fine.
**Screenshots …
> Updating of status options (#172) & Issue resolved
