phamos-eu/phamos

- phamos/phamos/doctype/accounting_receipt/accounting_receipt.js
- phamos/phamos/doctype/accounting_receipt/accounting_receipt.json
- phamos/phamos/doctype/accounting_receipt/accounting_receipt.py
- phamos/phamos/doctype/accounting_receipt/test_accounting_receipt.py
- phamos/phamos/doctype/accounting_receipt_timesheet/accounting_receipt_timesheet.json
- phamos/phamos/doctype/accounting_receipt_timesheet/accounting_receipt_timesheet.py
https://github.com/phamos-eu/phamos/issues/2
> feat: Accounting Receipt

- phamos/phamos/doctype/timesheet_record/timesheet_record.json
Added the todays date to "modification" in phamos/phamos/doctype/timesheet_record/timesheet_record.json
Addition to last PR https://github.com/phamos-eu/phamos/pull/19
> Date of modification changed to todays date

- phamos/phamos/doctype/timesheet_record/timesheet_record.json
- removed unused fields that have been hidden
https://git.phamos.eu/phamos/phamos/-/issues/3
> removing unused field timesheet_record.json

- phamos/phamos/doctype/timesheet_record/timesheet_record.json
> 20240401 merging into production

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
create Timesheet Record on click on Start button.
> feat:create timesheet record on click on start button.

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
> Timesheet Record Stop button add.

- phamos/patches.txt
- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
show assigned projects to logged in user
> show assigned projects to logged in user

- phamos/patches.txt
- phamos/patches/v1_0/add_property_for_timesheet_record.py
- phamos/phamos/doctype/timesheet_record/timesheet_record.py
- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
feat:time measurments correction in number cards,activity type mandatory property removed through patch, validation add for activity type on submit, add activity type on stop dialog box, remove activity type from start dialog box."
> Activity Type Update

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
1. Add Info from start Timesheet record to 'stop' dialog box.
2. add submitted hours column to project action panel.
> Add Submitted Hours & Short info from start screen to Project action panel.

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
1. Updated 'Customer' link reference in Project Action Panel.
2. Right click is working on  'Customer' link reference
> Update 'Customer' link reference in Project Action Panel.

- phamos/phamos/page/project_action_panel/project_action_panel.js
Add a button to redirect users to view timesheet records in calendar view
> feat:add button to see timesheet records calender view

- phamos/hooks.py
- phamos/phamos/doctype/have_a_great_day/have_a_great_day.js
- phamos/phamos/doctype/have_a_great_day/have_a_great_day.json
- phamos/phamos/doctype/have_a_great_day/have_a_great_day.py
- phamos/phamos/doctype/have_a_great_day/test_have_a_great_day.py
- phamos/public/js/have_a_great_day.js
- phamos/public/js/phamos.bundle.js
1.  "Login with your user ID. Ensure you have an employee record associated with your user ID. After logging in, a feedback dialog box will be displayed."
2. "Enter all data and save the dialog form."
3. A feedback record is created under the doctype 'Have a Great Day' for each user daily. Each user can create only one record per day."
> feat:created and update everyday feedback form have a great day

- phamos/patches.txt
- phamos/phamos/doctype/have_a_great_day/have_a_great_day.py
- phamos/phamos/doctype/phamos_settings/phamos_settings.json
- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
- phamos/public/js/have_a_great_day.js
Have a great day! (Thread)
https://chat.phamos.eu/phamos/pl/hkcp89ys63nxiyd91zobn7r49r
functionality added for - The dialog is displaying according to the user's time zone, which is fetched from the user's profile.
1. User zone is set to "Asia/Karachi"
2. In "Phamos Settings," set from_time and till_time to display the dialog box.
3. dialog is getting displayed at defined time duration.
"Added enable_feedback_dialog in 'Phamos Settings' to manage the feedback dialog box feature."
> feat:show dialog as per users time zone

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
https://git.phamos.eu/phamos/phamos/-/work_items/68
1. add task link field in start dialog box.
2. add task link field in stop dialog box.
timesheet record is getting created with or without task.
> timesheet record from project action panel without task or with task

- phamos/phamos/page/project_action_panel/project_action_panel.js
https://git.phamos.eu/phamos/phamos/-/work_items/84
Add assign_to button in Project Action Panel.
display button on tab All Projects
> Add 'Assign To ' button in project action panel.

- phamos/phamos/page/project_action_panel/project_action_panel.js
change spacing/order and/or add third column -  Project Action Panel
https://git.phamos.eu/phamos/phamos/-/work_items/92
> feat:exchange places of Expected Time and From Time.

- phamos/phamos/page/project_action_panel/project_action_panel.py
https://git.phamos.eu/phamos/phamos/-/issues/95
update calculation of total_hours_worked_in_this_month
> update calculation of total_hours_worked_in_this_month

- phamos/phamos/page/project_action_panel/project_action_panel.js
phamos/phamos#97
https://git.phamos.eu/phamos/phamos/-/issues/93
combine hours to one 'hours status' column-
> combine hours in to one column

- phamos/phamos/doctype/phamos_settings/phamos_settings.json
- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
> Revert "Update project action panel 1"

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
https://git.phamos.eu/phamos/phamos/-/work_items/84
https://git.phamos.eu/phamos/phamos/-/work_items/83
Dropdown options added for Assign Button-
If we select 'Self' - execute function to assign project ourself without dialog box.
If we select 'Others' - show 'assign to' dialog box.
In tab-'All Projects' - added project ,customer,assign button - 3 columns
> update all projects tab

- phamos/phamos/page/project_action_panel/project_action_panel.py
[update ](https://git.phamos.eu/phamos/phamos/-/work_items/83)
updated fetch all projects in all project tab- fetch projects which are not assigned to logged in user
> update fetch all projects query

- phamos/phamos/page/project_action_panel/project_action_panel.js
https://git.phamos.eu/phamos/phamos/-/work_items/83
reloading datatable on assigning new project from 'all projects' tab.
format code.
> reload datatable on assigning project

- phamos/phamos/page/project_action_panel/project_action_panel.js
https://git.phamos.eu/phamos/phamos/-/work_items/123
Shifted the Action column beside the Project column in the data table.
**Updated Column Classes:**
```
.dt-cell__content--col-5 and .dt-cell__content--header-5 { display: table-cell; }
→ Replaced with .dt-cell__content--col-6 and .dt-cell__content--header-6 { display: table-cell; }
```
We replaced column classes to reflect the updated column order, which also resulted in adjustments to their size.
**Before:**
**After:**
> Refactor : Shift Data Table Action column in project action panel

- phamos/phamos/page/project_action_panel/project_action_panel.js
**Issue** => https://git.phamos.eu/phamos/phamos/-/work_items/123
This PR implements [feature/issue details] for version-15. The changes have been applied to a new release branch created from the production version-15 to ensure a clean and focused implementation.
**Before:**
**After:**
> Moved 'Action' column next to 'Project' in DataTable

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
This pull request adds a `PULL_REQUEST_TEMPLATE.md` file to the `.github` directory. This template will be used to pre-populate the description field of new pull requests, ensuring consistency and completeness in the information provided by contributors.  This will streamline the code review process and make it easier for reviewers to understand the context and purpose of each pull request.
*   Created the `.github` directory (if it didn't exist).
*   Added the `PULL_REQUEST_TEMPLATE.md` file to the `.github` directory.
*   The template includes sections for describing the changes, related issues, testing done, screenshots (if applicable), and a checklist.  It encourages contributors to provide clear and concise information about their changes.
**Related …
> Add PULL_REQUEST_TEMPLATE.md

- phamos/phamos/doctype/recruitment_settings/recruitment_settings.js
- phamos/www/schedule_interview/index.css
- phamos/www/schedule_interview/index.html
- phamos/www/schedule_interview/index.py
- requirements.txt
Updating color scheme and fixing ics timezone issue
1. Updated UI color scheme of interview schedule page
2. Time format for HH:MM:SS to HH:MM on interview schedule page and ICS functionality
3. Replaced ICS generation with icalendar instead of ics
4. Added Custom fields and property Setters
- [Related to  Parent](https://git.phamos.eu/phamos/hr-department/-/issues/31)
- [GitLab Issue](https://git.phamos.eu/phamos/hr-department/-/work_items/32)
* Booked interview for job applicant
* Save ICS on calendar to test ensure correct timezone conversion
**Screenshots & GIFs (if applicable):**
- Updated color scheme on page:
- ICS 
[Screencast from 2025-03-17 14-17-55.webm](https://github.com/user-attachments/assets/bb8d1986-f61c-4e …
> automating interview process

- phamos/phamos/page/project_action_panel/project_action_panel.js
- phamos/phamos/page/project_action_panel/project_action_panel.py
**Issue:**  https://git.phamos.eu/phamos/phamos/-/issues/79
**Child Issue:**
1. https://git.phamos.eu/phamos/phamos/-/work_items/142
2. https://git.phamos.eu/phamos/phamos/-/work_items/122
**merge** child Issue [#122](https://git.phamos.eu/phamos/phamos/-/work_items/122), [#142](https://git.phamos.eu/phamos/phamos/-/work_items/142)  and optimize SQL queries using Frappe Query Builder
> merge updates from child feature branch for issue #79

- phamos/phamos/page/project_action_panel/project_action_panel.py
**issue:** https://git.phamos.eu/phamos/phamos/-/work_items/159
**Parent Issue:**  https://git.phamos.eu/phamos/phamos/-/issues/158
Declare the variable total_billable_time_str with a default value of "0 billable hours" to prevent the error UnboundLocalError: cannot access local variable 'total_billable_time_str' before it is assigned a value.
> fixed Issue #159: Total billable hours bug Project Action Panel

- phamos/phamos/doctype/implementation/implementation.py
**Parent:** https://git.phamos.eu/phamos/phamos/-/issues/146
**Child:**https://git.phamos.eu/phamos/phamos/-/work_items/149
This commit is related to the previous one. While testing some use cases, I discovered a change in the sales order query, so I modified it accordingly. Below is the reference PR -
https://github.com/phamos-eu/phamos/pull/129
> [#149][Minor changes in the implementation py file]

- phamos/phamos/doctype/implementation/implementation.py
**Parent:** https://git.phamos.eu/phamos/phamos/-/issues/146
**Child:** https://git.phamos.eu/phamos/phamos/-/work_items/149
This PR introduces a small change in the implementation file, which is related to the previous commit. Commit reference - https://github.com/phamos-eu/phamos/commit/9022929a869c7d5bc480633bc164e20118ad6171
> #149 issue - Not considering past data of SO, DN and SI

- phamos/phamos/doctype/implementation/implementation.json
**Make customer manadatory and allow for internal implementations (#169)**
*  Customer is manadory
*  user has option to select "Internal Implementation"
*  If "Internal implementation" is selected customer selection field is not mandatory and is hidden
Made changes in Implemetation Doctype
-  user has option to select "Internal Implementation"     (Check)
-  If "Internal implementation" is selected customer selection field is not mandatory and is hidden
-  and if it is not selected than customer is mandatory
https://git.phamos.eu/phamos/phamos/-/work_items/170
(this issue is done by @sayadeshmukh  but because of some PR conflicts @nasirkhansulaimankhail  asked me to do it again ,
but when the PR conflict resolved, then I …
> internal implementation check

- phamos/hooks.py
- phamos/phamos/doctype/implementation/implementation.js
- phamos/phamos/doctype/implementation/implementation.json
- phamos/phamos/doctype/implementation/implementation.py
- phamos/phamos/doctype/resource_planning/resource_planning.json
**Charting of Time spent on implementation (#161)**
Created a Graph with highchart to show billable Vs. Non-billable hours for the resource planning in the Implementation doctype
*  User can see billable time spent on implementation (per month)
* User can see non billable time spent on implementation (per month)
* User can see total time spent on implementation (per month)
[#179](https://git.phamos.eu/phamos/phamos/-/work_items/179)
Working fine on my local
**Screenshots & GIFs (if applicable):**
> Charting of Time spent on implementation (#161)

- phamos/phamos/doctype/implementation/implementation.py
Fields updated in implementation doctype, but not updated in the code so need to add those new fields in code to update status history table.
"Status Statement" is a new field added in the table before it was "status"; that's why it is not updating.
Updation:
Also, I added the trend field in the code, so the trend field in the history table also gets updated from the detail page.
Also, restrict the function to update only one row for one day, if some updation occurs on the same day, just update the fields.
**Issue:** https://git.phamos.eu/phamos/phamos/-/work_items/195
**Parent Issue:** https://git.phamos.eu/phamos/phamos/-/issues/162
Testing done on local also attached GIF.
**Screenshots & GIFs (if …
> Status History Tab (#162)
